version: '2.23.0'  # Версия Compose

services:
  my_app: test1:v1.1 # Имя сервиса
    build: .  # Указываем, что образ нужно собрать из Dockerfile в текущей директории
    container_name: my_python_container_test  # Имя контейнера
    volumes:
      - .:/app  # Монтируем текущую директорию в /app внутри контейнера
    command: python3 kvadratnoe_uravnenie.py  # Команда для запуска (если не указана в Dockerfile)
